# Generated by Django 5.0 on 2023-12-09 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='produtos',
            fields=[
                ('id_produto', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.TextField(max_length=99999)),
                ('descricao', models.TextField(max_length=99999)),
                ('quantidade', models.IntegerField()),
            ],
        ),
    ]
