# Generated by Django 5.0 on 2023-12-09 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cad_produto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='quantidade',
            field=models.TextField(max_length=99999),
        ),
    ]
